### ISSUE TITLE
Found Issues in Connect Page

### ISSUE THREAD

**Issue by nussarafirn** [Local-Connectivity-Lab/Local-Connectivity-Lab.github.io#1]
<img width="1338" alt="Screen Shot 2022-04-19 at 9 36 40 AM" src="https://user-images.githubusercontent.com/49351566/164052736-ae64888f-9445-468b-a579-39f6ec339f68.png">

Awesome work with the website! I just wanted to give you feedback on the issue that I found for the websites. The Locations section seems to have overlapping cards laying on top of it, this might be the layout issue.

The card descriptions still have the _asdf_ as a place holder description as well.

**Comment by infrared0** [comment]
content issue corrected! formatting issue currently being worked on by @marishuman.
